# Generated by Django 4.1.8 on 2024-07-13 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('semana', models.IntegerField(primary_key=True, serialize=False, verbose_name='Semana')),
                ('hh', models.IntegerField(verbose_name='Cantidad de horas estimadas')),
            ],
        ),
        migrations.CreateModel(
            name='Graficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(verbose_name='Semana')),
                ('hhRequerido', models.IntegerField(verbose_name='Cantidad de horas estimadas')),
                ('hhDisponible', models.IntegerField(verbose_name='Cantidad de horas estimadas')),
                ('utilización', models.FloatField(verbose_name='Cantidad de horas estimadas')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_hh_Detalle_Semanal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Semanal')),
                ('idTipoProyecto', models.CharField(max_length=10, verbose_name='Tipo de Proyecto')),
                ('numSemana', models.IntegerField(verbose_name='Número de Semana')),
                ('hh', models.IntegerField(verbose_name='Cantidad de horas')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Venta')),
                ('idTipoProyecto', models.CharField(max_length=10, verbose_name='Tipo de Proyecto')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Hh_Estimado_Detalle_Semanal',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='ID Estimado Detalle Semanal')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2024, 7, 12, 21, 7, 7, 433227), verbose_name='Fecha')),
                ('anio', models.IntegerField(default=2024, verbose_name='Año')),
                ('semana', models.IntegerField(default=31, verbose_name='Semana')),
                ('hh', models.IntegerField(verbose_name='Cantidad de horas estimadas')),
                ('idPerfilHhDetalleSemanal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.perfil_hh_detalle_semanal')),
                ('idVentas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ventas')),
            ],
        ),
    ]
