# Generated by Django 5.0.7 on 2024-07-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(verbose_name='Semana')),
                ('hhRequerido', models.IntegerField(verbose_name='Cantidad de horas estimadas')),
                ('hhDisponible', models.IntegerField(verbose_name='Cantidad de horas estimadas')),
                ('utilización', models.FloatField(verbose_name='Cantidad de horas estimadas')),
            ],
        ),
        migrations.CreateModel(
            name='Hh_Estimado_Detalle_Semanal',
            fields=[
                ('semana', models.IntegerField(primary_key=True, serialize=False, verbose_name='Semana')),
                ('hh', models.IntegerField(verbose_name='Cantidad de horas estimadas')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_hh_Detalle_Semanal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Semanal')),
                ('idTipoProyecto', models.CharField(max_length=10, verbose_name='Tipo de Proyecto')),
                ('numSemana', models.IntegerField(verbose_name='Número de Semana')),
                ('hh', models.IntegerField(verbose_name='Cantidad de horas')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Venta')),
                ('idTipoProyecto', models.CharField(max_length=10, verbose_name='Tipo de Proyecto')),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
    ]
