# Generated by Django 4.1.8 on 2024-07-14 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 21, 24, 32, 781400), verbose_name='Fecha'),
        ),
    ]
