# Generated by Django 4.1.8 on 2024-07-14 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hh_estimado_detalle_semanal_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 22, 12, 38, 191589), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Estimado Detalle Semanal'),
        ),
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='semana',
            field=models.IntegerField(verbose_name='Semana'),
        ),
    ]
