# Generated by Django 5.0.7 on 2024-07-14 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_utilización_graficos_utilizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 14, 17, 58, 5, 502176), verbose_name='Fecha'),
        ),
    ]
