# Generated by Django 5.0.7 on 2024-08-13 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_distribuidor_hh_proyectosaagrupar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 18, 33, 11, 59170), verbose_name='Fecha'),
        ),
    ]
