# Generated by Django 5.0.7 on 2024-08-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_hh_estimado_detalle_semanal_fecha'),
        ('core', '0025_remove_distribuidor_hh_horas_empleado_and_more'),
    ]

    operations = [
    ]
