# Generated by Django 5.1 on 2024-08-22 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_horasrequeridas_and_more'),
        ('core', '0026_merge_20240815_1734'),
    ]

    operations = [
    ]
