# Generated by Django 5.1 on 2024-08-22 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20240822_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hh_estimado_detalle_semanal',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 17, 58, 53, 84448), verbose_name='Fecha'),
        ),
    ]
